### ISSUE TITLE
Tomcat is running but application is not running inside tomcat.

### ISSUE THREAD

**Issue by ayanbasak** [jmGithub2021/iMediXcare#1]
We have followed Installation Guide pdf which provided in source code, by that we are able to run tomcat, but application is not running inside tomcat. Please help us to solve this issue, here are the lines which shown in terminal. 
```

ayan@Ayan:~/ayan/iMediXcare-main$ ./configure.sh 
Coniguring iMediX Web

---------------------
sed: can't read /home/ayan/ayan/iMediXcare-main//Tomcat9/webapps/iMediXcare/config.info: No such file or directory
sed: can't read /home/ayan/ayan/iMediXcare-main//Tomcat9/webapps/iMediXcare/config.info: No such file or directory
sed: can't read /home/ayan/ayan/iMediXcare-main//Tomcat9/webapps/iMediXcare/config.info: No such file or directory
sed: can't read /home/ayan/ayan/iMediXcare-main//Tomcat9/webapps/iMediXcare/config.info: No such file or directory
sed: can't read /home/ayan/ayan/iMediXcare-main//Tomcat9/webapps/iMediXcare/config.info: No such file or directory
sed: can't read /home/ayan/ayan/iMediXcare-main//Tomcat9/webapps/iMediXcare/config.info: No such file or directory
sed: can't read /home/ayan/ayan/iMediXcare-main//Tomcat9/webapps/iMediXcare/config.info: No such file or directory
Coniguring iMediX Business Logic

--------------------------------
Database name [imedixdb4]: imedixcaredb
Database username [imedix]: root
Database password [imedix12]: xxxxxxxxxxxx
Coniguring iMediX Source Code (Server Module)
---------------------------------------------
Coniguring iMediX Source Code (Tomcat Module)
---------------------------------------------
ayan@Ayan:~/ayan/iMediXcare-main$ ./build.sh 
Building iMediX-Care Server Module
-----------------------------
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Warning: generation and use of skeletons and static stubs for JRMP	
is deprecated. Skeletons are unnecessary, and static stubs have	
been superseded by dynamically generated stubs. Users are	
encouraged to migrate away from using rmic to generate skeletons and static	
stubs. See the documentation for java.rmi.server.UnicastRemoteObject.
Building iMediX-Care Tomcat Module
-----------------------------
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: dataobj.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: dataobj.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
cp: target '/home/ayan/ayan/iMediXcare-main/Tomcat9/webapps/iMediXcare/WEB-INF/lib' is not a directory
done
ayan@Ayan:~/ayan/iMediXcare-main$ ./run.sh 
Stopping all junk java processes
--------------------------------
[sudo] password for ayan: 
Stopping Tomcat Server
----------------------
Using CATALINA_BASE:   /home/ayan/ayan/iMediXcare-main/Tomcat9
Using CATALINA_HOME:   /home/ayan/ayan/iMediXcare-main/Tomcat9
Using CATALINA_TMPDIR: /home/ayan/ayan/iMediXcare-main/Tomcat9/temp
Using JRE_HOME:        /home/ayan/ayan/iMediXcare-main/jdk11/
Using CLASSPATH:       /home/ayan/ayan/iMediXcare-main/Tomcat9/bin/bootstrap.jar:/home/ayan/ayan/iMediXcare-main/Tomcat9/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Sep 08, 2022 2:36:36 PM org.apache.catalina.startup.Catalina stopServer
SEVERE: Could not contact [localhost:8005] (base port [8005] and offset [0]). Tomcat may not be running.
Sep 08, 2022 2:36:36 PM org.apache.catalina.startup.Catalina stopServer
SEVERE: Error stopping Catalina
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:667)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:391)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:481)

Starting Tomcat Server
---------------------
Using CATALINA_BASE:   /home/ayan/ayan/iMediXcare-main/Tomcat9
Using CATALINA_HOME:   /home/ayan/ayan/iMediXcare-main/Tomcat9
Using CATALINA_TMPDIR: /home/ayan/ayan/iMediXcare-main/Tomcat9/temp
Using JRE_HOME:        /home/ayan/ayan/iMediXcare-main/jdk11/
Using CLASSPATH:       /home/ayan/ayan/iMediXcare-main/Tomcat9/bin/bootstrap.jar:/home/ayan/ayan/iMediXcare-main/Tomcat9/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
Tomcat started.
Starting iMediX-Care Business Logic
------------------------------
lib/aspectjweaver-1.6.2.jar
lib/imedix.jar
lib/logger.jar
lib/imedixservlets.jar
lib/phiv.jar
lib/iMediXBusinessLogic.jar
lib/onlinegc.jar
lib/commons-io-2.4.jar
lib/json-simple-1.1.1.jar
lib/mysql-connector-java-5.1.6.jar
lib/ftp.jar
lib/tuberculosis.jar
this address=Ayan/127.0.1.1,port=1099
Creating remote object
 ```
**Here is Tomcat Manager Screenshot:**
![Tomcat Manager Screenshot](https://user-images.githubusercontent.com/60224324/189101074-85de261e-1d2e-427c-bc24-a3616a35edbe.png)

**Comment by surajitiitkgp** [comment]
Place the **_iMediXcare_** folder in the **_Tomcat9/webapps/_** directory. Then follow the instruction 5-8 from the installation manual.

**Comment by ayanbasak** [comment]
Thanks sir for your  solution, now our application is properly running. but still we have some issue we are not able to login by username(admin) and password(admin). in login screen it shows " Wrong username and password". it will be better if we know that we needs to add/modify any file for database connection in project or there have any issue with database. thank you.

```
Error found java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property. : Select uid,name,crtdate,type,phone,address,emailid,qualification,designation,dis,rg_no,center,active,verifemail,verifphone from login where ((binary uid=? and binary pwd=AES_ENCRYPT(?, UNHEX(SHA2(?,512)))) or (binary emailid=? and binary pwd=AES_ENCRYPT(?, UNHEX(SHA2((select uid from login where emailid=?),512)))) or (binary phone=? and binary pwd=AES_ENCRYPT(?, UNHEX(SHA2((select uid from login where phone=?),512))))) and verified=?
Error found java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property. : Select uid,name,crtdate,type,phone,address,emailid,qualification,designation,dis,rg_no,center,active,verifemail,verifphone from login where ((binary uid=? and binary pwd=AES_ENCRYPT(?, UNHEX(SHA2(?,512)))) or (binary emailid=? and binary pwd=AES_ENCRYPT(?, UNHEX(SHA2((select uid from login where emailid=?),512)))) or (binary phone=? and binary pwd=AES_ENCRYPT(?, UNHEX(SHA2((select uid from login where phone=?),512))))) and verified=?
Log Path : /serverApp/SystemLog/09092022AccessLog.xml
```
